# Generated by Django 4.2.7 on 2024-09-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_rolemaster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelActionMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('next_action', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_level_action_mapping',
            },
        ),
        migrations.CreateModel(
            name='WorkflowDetail',
            fields=[
                ('request_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id_id', models.ForeignKey(blank=True, db_column='user_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_F', to='Masters.user')),
            ],
            options={
                'db_table': 'tbl_workflow_details',
            },
        ),
        migrations.CreateModel(
            name='ServiceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('role_name', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ser_id_id', models.ForeignKey(blank=True, db_column='ser_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ser_id_id_F', to='Masters.servicemaster')),
            ],
            options={
                'db_table': 'tbl_service_matrix',
            },
        ),
    ]
