# Generated by Django 4.2.7 on 2024-09-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_levelactionmapping_workflowdetail_servicematrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_document_master',
            },
        ),
        migrations.AlterField(
            model_name='levelactionmapping',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CitizenDocument',
            fields=[
                ('userdocumentid', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_id_id', models.ForeignKey(blank=True, db_column='doc_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_id_id_F', to='Masters.documentmaster')),
            ],
            options={
                'db_table': 'tbl_citizen_document',
            },
        ),
    ]
