# Generated by Django 4.2.7 on 2024-09-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_alter_citizendocument_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicematrix',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
